### PR TITLE
All branches changes

### PR DESCRIPTION
**Pull request by CreeperPlanet26**
All branched need some changes. I'm gonna do those changes in this pr

### CODE REVIEW

**Comment by CreeperPlanet26** [comment]
I added trailing comma as it is good practice to always have one. It will give error if you dont put it.

**Comment by CreeperPlanet26** [comment]
Please review

**Comment by Maxisthemoose** [comment]
Looks good 👍

**Comment by CreeperPlanet26** [comment]
ok u can merge

**Pull request merged**
