### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by Maxisthemoose**
Notifications stuffs

### CODE REVIEW

**Comment by CreeperPlanet26** [comment]
> wdym? where? the variable name stayed the same

Oh nvm I don't see that u did this before
 ```js
const botId = req.params
```

**Comment by Maxisthemoose** [comment]
> 
> 
> > wdym? where? the variable name stayed the same
> 
> Oh nvm I don't see that u did this before
> 
> ```js
> const botId = req.params.id
> ```
> 
> why can i edit your comment wtf
> 
> Idk it's a GitHub thing

tbh i have no idea how to reply

**Comment by Maxisthemoose** [comment]
🤷

**Comment by CreeperPlanet26** [comment]
This is done and everything works now.

**Pull request merged**
